import sqlite3

connection = sqlite3.connect("films.db")
cursor = connection.cursor()

cursor.execute("create table films (release_year integer, title text, main_genre text, isWatched boolean)")

release_list = [
	(2010, "Gallants", "Action", False),
	(2006, "Apocalypto", "Sci-fi", False),
	(2017, "War of the Planet of the Apes", "Sci-fi", False),
	(2001, "One Night at Mccools", "Action", False),
	(2015, "Victor Frankenstein", "Horror", False),
	(2019, "Aniara", "Sci-fi", False),
	(2012, "Abraham Lincoln Vampire Hunter", "Action", True),
	(1998, "Dark City", "Sci-fi", True),
	(2015, "Sicario", "Action", True),
	(2014, "Ex Machina", "Sci-fi", True),
	(2018, "MI: Fallout", "Action", True),
	(2013, "Hansed and Gretel Witch Hunters", "Action", True),
	(2013, "Jack the Giant Slayer", "Fantasy", True),
	(2011, "Conan", "Action", True),
	(2014, "Hercules", "Action", True),
	(2012, "Prometheus", "Sci-fi", False),
	(2012, "Battleship", "Sci-fi", False),
	(2018, "The Predator", "Action", False),
	(2010, "Predators", "Action", True),
	(2018, "Upgrade", "Action", True),
	(2015, "Bone Tomahawk", "Horror", True),
	(2017, "Brawl in Cellblock 99", "Action", True),
	(2004, "Kung fu hustle", "Comedy", True),
	(1992, "Dracula", "Fantasy", True),
	(2007, "Yout without Youth", "Fantasy", False),
	(2016, "The BFG", "Fantasy", True),
	(2015, "Monster Hunt", "Action", False),
	(2010, "Kickass", "Action", True),
	(2011, "Aliens and Cowboys", "Sci-fi", True),
	(2011, "Rise of the planet of the apes", "Sci-fi", False),
	(2009, "Splice", "Action", False),
	(2009, "District 9", "Sci-fi", True),
	(2012, "Chronicle", "Fantasy", False),
	(2006, "Crank", "Action", True),
	(2009, "Crank 2", "Action", True),
	(1984, "Dune", "Fantasy", False),
	(2007, "Stardust", "Adventure", False),
	(2020, "Stardust", "Biography", False),
	(1996, "Sling Blade", "Action", False),
	(2018, "Mortal Engine", "Action", False),
	(1987, "Princess Bride", "Fantasy", False),
	(2016, "The Belko Experiment", "Thriller", True),
	(2000, "Joint Security Area", "Action", False),
	(1995, "The Blade", "Action", True),
	(1985, "Police Story", "Action", False),
	(1988, "Police Story 2", "Action", False),
	(1992, "Police Story 3: Supercop", "Action", False),
	(1996, "Police Story 4", "Action", False),
	(2017, "Bad Match", "Action", False),
	(2017, "Sound of Silence", "Drama", False),
	(2018, "Dragged Across Concrete", "Thriller", True),
	(2014, "Matador", "Thriller", False),
	(1989, "Tango and Cash", "Action", True),
	(2007, "There Will Be Blood", "Drama", False),
	(1999, "The Boondock Saints", "Action", True),
	(2020, "Riders of Justice", "Action", False),
	(2020, "Possessor", "Horror", False),
	(2013, "Elysium", "Sci-fi", True),
	(2010, "I Saw the Devil", "Action", False),
	(2013, "The Last Stand", "Action", True),
	(2009, "Shinjuku Incident", "Action", False),
	(1986, "Armour of God", "Action", False),
	(1991, "Armour of God 2", "Action", False),
	(2012, "Armour of God 3", "Action", False),
	(1998, "Who Am I", "Action", False),
	(1987, "Project A part II", "Action", False),
	(1989, "Miracles", "Action", False),
	(2006, "Rob-B-Hood", "Action", False),
	(1989, "City Hunter", "Action", False),
	(1982, "Fantasy Mission Force", "Action", False),
	(1992, "Twin Dragons", "Action", False),
	(1983, "Winners and Sinners", "Action", False),
	(2013, "Oz the Great and Powerful", "Fantasy", False),
	(2011, "Rango", "Animation", True),
	(2015, "Turbo Kid", "Adventure", False),
	(2009, "Pandorum", "Action", False),
	(2004, "Primer", "Sci-fi", False),
	(2011, "Contagion", "Sci-fi", True),
	(2017, "Everything Beautiful is Far Away", "Fantasy", False),
	(2009, "Fantastic Mr Fox", "Animation", False),
	(2020, "Doctor Dolittle", "Fantasy", True),
	(1988, "Red Heat", "Action", False),
	(2014, "Divergent", "Action", False),
	(2015, "Legend", "Crime", False),
	(2021, "Pig", "Drama", True),
	(2014, "Hana and Alice", "Drama", False),
	(2012, "The Same Storm", "Drama", False),
	(2003, "Pieces of April", "Comedy", False),
	(2007, "Dan in Real Life", "Comedy", False),
	(2017, "Suburbicon", "Comedy", False),
	(1998, "Funny Games", "Comedy", False),
	(2018, "Widows", "Crime", False),
	(2022, "Fresh", "Horror", False),
	(2009, "Big Fan", "Comedy", False),
	(2017, "I, Tonya", "Comedy", False),
	(2018, "Little Forest", "Drama", False),
	(1959, "Good Morning", "Comedy", False),
	(2001, "Donnie Darko", "Mystery", False),
	(2017, "Ingrid Goes West", "Comedy", False),
	(2016, "Colossal", "Comedy, Drama, Fantasy", False),
	(2015, "Rock the Kasbah", "Comedy", False),
	(2017, "I don't feel at Home in this World Anymore", "Comedy, Crime", False),
	(2017, "Brad's Status", "Drama", False),
	(2017, "The Florida Project", "Drama", False),
	(2017, "The Killing a Sacred Deer", "Drama, Horror", False),
	(2009, "Dogtooth", "Drama, Thriller", False),
	(2017, "The Lobster", "Comedy, Drama", False),
	(2017, "A Ghost Story", "Drama, Fantasy", False),
	(2017, "Mayhem", "Action, Comedy", False),
	(2013, "Dallas Buyers Club", "Biography, Drama", False),
	(2014, "Paddington", "Adventure, Comedy, Family", True),
	(2016, "The Lost City of Z", "Adventure, Drama", False),
	(2011, "Albatross", "Drama", False),
	(2014, "What We Do in the Shadows", "Comedy", True),
	(2016, "Brothers Grimsby", "Comedy", True),
	(2018, "Summer of 84", "Drama, Horror", False),
	(2018, "Game Night", "Comedy, Adventure", True),
	(2018, "Isle of Dogs", "Animation, Adventure", False),
	(2016, "Director's Cut", "Comedy, Crime, Horror", False),
	(2017, "Captain Underpants", "Animation, Comedy", False),
	(2009, "Party Down", "Comedy, Drama", False),
	(2019, "Lighthouse", "Drama", False),
	(2012, "Dark Shadows", "Comedy", True),
	(2017, "Big Sick", "Drama, Comedy", True),
	(2019, "Paddleton", "Drama, Comedy", False),
	(2010, "Cyrus", "Comedy, Drama, Romance", False),
	(2012, "This is 40", "Comedy, Drama", False),
	(2010, "Greenberg", "Comedy, Drama, Romance", False),
	(2012, "The Comedy", "Comedy, Drama", False),
	(2015, "Creed", "Drama", False),
	(2012, "Passion", "Adventure, Mystery, Drama", False),
	(2013, "Saving Mr Banks", "Comedy", False),
	(2013, "Captain Phillips", "Drama", False),
	(2014, "Gone Girl", "Thriller, Crime, Mystery", True),
	(2002, "Panic Room", "Crime, Thriller", False),
	(2019, "The Fanatic", "Comedy, Drama", False),
	(2017, "The Thoroughbreds", "Comedy, Crime", False),
	(1988, "Heathers", "Comedy, Crime", False),
	(2018, "American Animals", "Crime, Drama", False),
	(2018, "Doris", "Comedy", False),
	(2005, "The Baxter", "Comedy, Romance", False),
	(2016, "Pee Wee Big Holiday", "Comedy, Adventure", False),
	(2009, "Observe and Report", "Comedy, Crime", False),
	(1974, "Blazing Saddles", "Comedy, Western", False),
	(2002, "Better Luck Tomorrow", "Crime", False),
	(2016, "The Mermaid", "Comedy", True),
	(1984, "Top Secret", "Comedy, Action", False),
	(2016, "The Greasy Strangler", "Comedy, Crime", False),
	(2007, "Tim and Eric", "Comedy", False),
	(2012, "Tim and Eric", "Comedy", False),
	(2013, "Tim and Eric", "Comedy", False),
	(2019, "Booksmart", "Comedy", False),
	(2017, "Coco", "Comedy, Animation, Family", True),
	(2010, "Beyond the Rainbow", "Horror, Mystery, Sci-fi", False),
	(2019, "The Favorite", "Drama", False),
	(1982, "Sophie's Choice", "Drama, Romance", False),
	(2018, "Clovehitch Killer", "Crime, Mystery", True),
	(1979, "Apocalypse Now", "War, Drama", False),
	(2018, "The Favourite", "Comedy, Drama", False),
	(2007, "Freedom Writers", "Crime", False),
	(2009, "3 Idiots", "Comedy, Drama", False),
	(2015, "I Saw the Light", "Drama, Music", False),
	(2013, "The Secret Life of Walter Mitty", "Adventure, Comedy", False),
	(2016, "Hacksaw Ridge", "War, Drama", False),
	(2016, "A Monster Calls", "Drama, Fantasy", False),
	(2009, "Fanboys", "Comedy", False),
	(2005, "Unleashed", "Comedy", False),
	(2016, "Unleashed", "Comedy, Romance, Fantasy", False),
	(1983, "The Keep", "Drama, Fantasy, Horror", False),
	(1977, "Eraserhead", "Fantasy, Horror", False),
	(1962, "Lolita", "Drama, Romance", False),
	(2016, "Lolita", "Drama, Romance", False),
	(1959, "Rio Bravo", "Western", False),
	(1981, "Blowout", "Crime, Mystery", False),
	(1953, "Monsieur Hulot's Weekend", "Comedy", False),
	(2003, "Dogville", "Crime", False),
	(1999, "Audition", "Horror, Mystery", False),
	(1995, "Friday", "Comedy, Drama", False),
	(2003, "Memories of a Murder", "Crime, Mystery", False),
	(2004, "Team America", "Comedy", False),
	(2005, "My Big Fat Independent Film", "Comedy", False),
	(2015, "Welcome to Me", "Comedy", False),
	(2015, "Poltergeist", "Comedy", False),
	(2015, "The Overnight", "Comedy, Mystery", False),
	(2002, "Men with Brooms", "Comedy, Romance", False),
	(2015, "The 33", "Drama, History", False),
	(2019, "The Art of Self-Defense", "Comedy, Crime", True),
	(1998, "Dirty Work", "Comedy", False),
	(2015, "Inside Out", "Comedy, Family", True),
	(2015, "Maggie", "Drama, Horror", True),
	(2001, "Wet Hot American Summer", "Comedy", False),
	(2018, "Rust Creek", "Crime, Thriller", False),
	(2019, "Sea Fever", "Horror, Mystery", False),
	(2020, "The Kid Detective", "Mystery, Thriller", True),
	(2001, "All About Lily Chou", "Crime, Music", False),
	(2017, "The Little Hours", "Comedy", False),
	(2019, "Oh, Ramona!", "Comedy, Romance", False),
	(2017, "Lady-like", "Comedy, Romance", False),
	(2008, "Sex Drive", "Comedy, Romance", False),
	(2018, "The Breaker Upperers", "Comedy", False),
	(2014, "The Grand Budapest Hotel", "Comedy, Adventure", True),
	(2016, "Brahman Naman", "Comedy", False),
	(2020, "The Lovebirds", "Comedy, Romance", False),
	(2017, "The Incredible Jessica James", "Comedy", False),
	(2019, "Someone Great", "Comedy, Romance", False),
	(1998, "Happiness", "Comedy, Drama", False),
	(1993, "Bad Boy Bubby", "Comedy, Crime", False),
	(2016, "Personal Shopper", "Mystery, Thriller", False),
	(2014, "The Interview", "Comedy", True),
	(2015, "Into the Forest", "Thriller", False),
	(2007, "Under the Skin", "Horror, Mystery", False),
	(2015, "Green Room", "Crime, Horror", False),
	(2005, "Brick", "Crime, Mystery", False),
	(2016, "The Invisible Guest", "Crime, Mystery", False),
	(2019, "Good Boys", "Adventure, Comedy", False),
	(2011, "Bridesmaids", "Comedy, Romance", True),
	(2002, "National Lampoon", "Comedy", False),
	(1994, "Exit to Eden", "Comedy, Crime", False),
	(1978, "National Lampoon's Animal House", "Comedy", False),
	(2007, "Good Luck Chuck", "Comedy, Romance", False),
	(2007, "National Lampoon's Spring Break", "Comedy", False),
	(2000, "100 Girls", "Comedy, Romance", False),
	(2006, "Accepted", "Comedy", False),
	(1984, "Bachelor Party", "Comedy", False),
	(2008, "Forgetting Sarah Marshall", "Comedy, Romance", False),
	(2006, "Beerfest", "Comedy", False),
	(2004, "Harold and Kumar Go to White Castle", "Comedy", True),
	(2008, "Harold and Kumar Escape Guantanamo Bay", "Comedy", False),
	(2007, "YPF", "Comedy", False),
	(2008, "Coming Soon", "Comedy", False),
	(2012, "Project X", "Comedy, Highschool", True),
	(2011, "Midnight in Paris", "Comedy, Romance", False),
	(2007, "Lars and the Real Girl", "Comedy, Romance", False),
	(2009, "Mula Rise of a Warrior", "Adventure, Drama", False),
	(2011, "Your Highness", "Comedy, Adventure", False),
	(2016, "Pride and Prejudice and Zombies", "Drama, Romance, Fantasy", True),
	(2018, "Leave no Trace", "Adventure, Drama", False),
	(2018, "Blindspotting", "Crime, Comedy", False),
	(2018, "Burning", "Mystery, Thriller", False),
	(2018, "Searching", "Horror, Mystery", False),
	(2018, "The Night is Short, Walk on Girl", "Adventure, Comedy, Animation", False),
	(2018, "Roma", "Drama", False),
	(2018, "Eighth Grade", "Drama, Family", True),
	(2017, "Paddington 2", "Drama, Comedy, Family", False),
	(2004, "Down to the Bone", "Drama", False),
	(2016, "Hell or High Water", "Crime, Thriller", False),
	(1970, "Kelly's Heroes", "Comedy, War, Adventure", False),
	(1998, "April Story", "Drama, Romance", False),
	(2016, "Mike and Dave Need Wedding Dates", "Comedy, Romance", False),
	(2017, "It Comes at Night", "Horror", False),
	(2016, "Raw", "Horror", False),
	(2020, "The Invisible Man", "Horror, Sci-fi", True),
	(2019, "Trick or Treat", "Horror", False),
	(2018, "Mandy", "Horror, Fantasy", False),
	(2018, "Haloween", "Horror", False),
	(2018, "Overlord", "Horror, War, Sci-fi", True),
	(2017, "Gerald's Game", "Horror, Thriller", True),
	(2013, "Oculus", "Horror", False),
	(2018, "Apostle", "Horror, Fantasy", False),
	(2015, "The Blackcoat's Daughter", "Horror", False),
	(2010, "Insidious", "Horror, Mystery", False),
	(2019, "Doctor Sleep", "Horror, Fantasy", False),
	(2019, "Ready or Not", "Horror, Action, Comedy", False),
	(2018, "Hereditary", "Horror, Mystery", False),
	(2019, "Us", "Horror, Mystery", False),
	(2014, "It Follows", "Horror, Mystery", True),
	(2017, "Mother!", "Horror, Mystery", False),
	(2015, "Hidden", "Horror, Sci-fi, Mystery", False),
	(2012, "Sinister", "Horror, Mystery", False),
	(2018, "Annihilation", "Horror, Sci-fi, Mystery", True),
	(2016, "Don't Breathe", "Horror, Thriller", False),
	(2017, "Wish Upon", "Horror, Fantasy", False),
	(2012, "Maniac", "Horror, Thriller", False),
	(2006, "Slither", "Horror, Comedy, Thriller", False),
	(2015, "Krampus", "Comedy, Drama, Fantasy", False),
	(2015, "Krampus: The Reckoning", "Horror", False),
	(2012, "Excision", "Horror, Comedy, Drama", False),
	(2019, "Child's Play", "Horror, Sci-fi", False),
	(2018, "Cloverfield Paradox", "Horror, Crime", False),
	(2016, "Neon Demon", "Horror, Thriller, Erotik", False),
	(2014, "Clown", "Horror, Thriller", False),
	(2021, "The Black Phone", "Horror, Crime", False),
	(1994, "New Nightmare", "Horror, Fantasy", False),
	(2010, "The Last Circus", "Adventure, Comedy, Drama", False),
	(2011, "Cabin in the Woods", "Horror, Comedy, Sci-fi", True),
	(2017, "The Bye Bye Man", "Horror, Fantasy", False),
	(2008, "Lake Mungo", "Horror, Mystery", False),
	(2009, "Drag Me to Hell", "Horror", True),
	(2005, "The Descent", "Horror, Adventure, Thriller", False),
	(2021, "Censor", "Horror, Mystery", False),
	(2018, "Puppet Master", "Comedy, Horror", False),
	(2011, "Close to You", "Comedy, Romance", False),
	(2013, "The Green Inferno", "Horror, Adventure", False),
	(2007, "Flight of the Concords", "Comedy, Music", False),
	(2014, "Backcountry", "Horror, Adventure", False),
	(2016, "Hush", "Horror, Crime, Thriller", True),
	(2003, "A Tale of Two Sisters", "Horror, Mystery", False),
	(2016, "The Wailing", "Horror, Mystery", True),
	(2014, "Starry Eyes", "Horror, Mystery", False),
	(2017, "The Florida Project", "Drama", False),
	(2021, "Red Rocket", "Comedy, Drama", False),
	(2015, "Tangerine", "Comedy, Drama, Crime", False),
	(2004, "Take Out", "Drama", False),
	(1973, "Badland", "Action, Crime", False),
	(2019, "Verotika", "Horror, Erotik", False),
	(1984, "Dune", "Fantasy", False),
	(2000, "Dune", "Fantasy", True),
	(1986, "Short Circuit", "Comedy, Sci-fi", False),
	(2009, "Terminator Salvation", "Action", False),
	(1990, "Total Recall", "Action", True),
	(2014, "Robocop", "Action", True),
	(1991, "Samurai Cop", "Action", False),
	(2020, "Psycho Goreman", "Fantasy, Comedy", False),
	(2014, "The Editor", "Comedy, Crime, Horror", False),
	(2011, "Twixt", "Comedy, Horror", False),
	(2009, "Tetro", "Drama", False),
	(1985, "Gotcha!", "Comedy, Action", True),
	(2015, "Into the Grizzly Maze", "Action", False),
	(1965, "Faster, Pussycat! Kill! Kill!", "Action, Comedy", False),
	(1976, "Up!", "Action, Comedy", False),
	(1996, "Dating the Enemy", "Comedy, Fantasy, Romance", False),
	(2002, "Secretary", "Comedy, Drama, Romance", False),
	(1995, "The Steal", "Comedy, Thriller", False),
	(1984, "Friday the 13th part IV", "Horror", False),
	(1980, "Canibal Holocaust", "Horror", False),
	(2014, "Canibal Holocaust", "Horror", False),
	(1998, "The Last Broadcast", "Horror", False),
	(2017, "Pieles", "Drama, Comedy", False),
	(2001, "Gamer", "Comedy, Sci-fi", False),
	(1998, "Hideous Kinky", "Action, Drama, Romance", False),
	(1998, "Thursday", "Action, Comedy, Crime", False),
	(2003, "The Order", "Horror, Mystery, Thriller", True),
	(2021, "Titane", "Horror, Sci-fi", False),
	(1986, "Blue Velvet", "Crime, Drama, Mystery", False),
	(1967, "Belle de Jour", "Drama, Romance", False),
	(1972, "The Discret Charm of the Bourgeoisie", "Comedy", False),
	(1962, "The Extermintating Angel", "Drama, Fantasy", False),
	(2006, "The Exterminating Angels", "Drama, Fantasy", False),
	(1950, "Los Olvidados", "Crime", False),
	(1935, "Anna Karenina", "Drama, Romance", False),
	(1948, "Anna Karenina", "Drama, Romance", False),
	(1997, "Anna Karenina", "Drama, Romance", False),
	(2012, "Anna Karenina", "Drama, Romance", False),
	(1983, "Zelig", "Comedy", False),
	(1963, "8 1/2", "Drama", False),
	(1974, "China Town", "Drama, Mystery, Thriller", False),
	(1969, "Butch Cassidy", "Crime, Drama", False),
	(1973, "Paper Moon", "Crime, Drama, Comedy", False),
	(1990, "Hunt for the Red October", "Action, Adventure, Thriller", False),
	(1986, "Big Trouble in Little China", "Adventure, Comedy", False),
	(2015, "Call Me Lucky", "Documentary", False),
	(2014, "Lost Souls: The Doomed Journey of Richard Stanley's Dr Moreau", "Documentary", False),
	(2020, "Not Going Down", "Documentary", False),
	(2013, "Jadorowski", "Documentary", False),
	(1982, "Koyaanisqatsi", "Documentary, Music", False),
	(1999, "Eyes Wide Shut", "Thriller", True),
	(1999, "Ninth Gate", "Mystery, Thriller, Fantasy", True),
	(1994, "Speed", "Action, Thriller", True),
	(2006, "The Host", "Horror, Adventure", True),
	(1993, "Dazed and Confused", "Comedy", False),
	(1997, "Mr Nice Guy", "Action", False),
	(1997, "Copland", "Crime", False),
	(1991, "Hanging with the Homeboys", "Comedy, Drama", False),
	(2008, "The Wrestler", "Drama, Sport", True),
	(1999, "Galaxy Quest", "Comedy, Sci-fi", True),
	(2020, "Minari", "Drama, Family", True),
	(2019, "Parasite", "Drama, Crime", True),
	(2022, "Everything Everywhere All at Once", "Comedy, Action, Fantasy, Drama", True),
	(2022, "Black Phone", "Horror, Crime, Thriller, Fantasy", True),
	(2014, "As Above So Bellow", "Horror, Mystery", False),
	(2011, "Margin Call", "Drama, Thriller", False),
	(2001, "Wet Hot American Summer", "Comedy, Romance", False),
	(2012, "Piranha 3DD", "Comedy, Horror", False),
	(2019, "The Farewell", "Comedy", False),
	(2018, "Crazy Rich Asians", "Comedy", False),
	(2011, " Wuthering Heights", "Drama", False),
	(1989, "Gleaming The Cube", "Adventure", False),
	(1998, "Elizabeth", "Drama, History", False)
]

cursor.executemany("insert into films values (?,?,?,?)", release_list)
connection.commit()
#print databse rows
#for row in cursor.execute("select * from films where main_genre like '%Fantasy%'"):
#	print(row)

#print("****************************")

#cursor.execute("select * from films where release_year > 2018")
cursor.execute("select * from films")
film_search = cursor.fetchall()
print(film_search)

connection.close()